// Fictional demo scenarios for the Payments pack. Nothing here is real: the merchants,
// people, orders and amounts are all invented.
import { readFile } from 'node:fs/promises';

const pack = JSON.parse(await readFile(new URL('../../site/packs/payments.json', import.meta.url), 'utf8'));
const U = { unreviewed: true };
const s = (role, input, reason, tools, reply, tag = '', note = null, extra = {}) => ({ role, input, reason, tools, reply, tag, note, ...extra });
const refund = (request, text) => ['Look up the refund', 'get_refund', request, text];
const payout = (request, text) => ['Look up the payout', 'get_payout', request, text];
const decline = (request, text) => ['Look up the decline', 'get_decline_reason', request, text];
const dispute = (request, text) => ['Look up the dispute', 'get_dispute', request, text];
const terms = (request, text) => ['Read the merchant’s terms', 'get_merchant_terms', request, text];
const policy = (request, text) => ['Search the help centre', 'search_help_center', request, text];

export default {
  pack, prefix: 'pay', personLabel: 'Customer',
  inputLabels: { cardholder: 'Cardholder', merchant: 'Merchant', 'ops agent': 'Ops agent' },
  releases: [['v1.1 confirmation step', 14], ['v1.2 merchant terms lookup', 28]],
  judge: { key: 'promises-an-outcome', change: 'Treats “usually” and “typically” as fine, firm dates as a fail',
    extraRule: 'A typical range (“usually 5 to 10 working days”) is a Pass. A firm date or a guaranteed result that the record does not show is a Fail.',
    failCritique: 'The person wanted to know what will happen. The reply gives a firm date or a guaranteed result that the record does not support, so it does not meet the criterion.',
    passCritique: 'The person wanted to know what will happen. The reply states what the record shows and gives no guarantee, so it meets the criterion.' },
  tests: [[1, null], [5, false], [8, true], [6, true], [2, true], [13, false]],
  failureModes: {
    'pending-as-done': { name: 'Says it’s done when it’s still pending', definition: 'Tells the person a refund or payout is complete when the record shows it pending, in transit or on hold.',
      boundaries: 'In: any status stronger than the record. Out: the right status in clumsy words.', fix: 'Make the reply quote the status field instead of paraphrasing it.',
      measure: 'A code check comparing the status in the reply with the status the tool returned.', handle: 'code_check', handleWhy: 'The reply can be compared with the status the tool returned, using a simple rule.', chosen: 'code_check', locked: true },
    'promises-an-outcome': { name: 'Promises a date or result it can’t guarantee', definition: 'Gives a firm date or a guaranteed result for a refund, dispute or review that the bank, the card scheme or another team decides.',
      boundaries: 'In: “you will win”, “by Friday”, “guaranteed”. Out: “usually 5 to 10 working days”.', fix: 'Add an instruction: give typical ranges, never firm dates, for anything a third party decides.',
      measure: 'An LLM judge: whether a sentence is a promise needs judgement.', handle: 'judge', handleWhy: 'Whether a sentence is a promise or a typical range depends on wording, so it needs judgement.', chosen: 'judge', locked: true },
    'wrong-decline-advice': { name: 'Wrong advice on a declined payment', definition: 'Tells the person to retry a payment that the bank has refused for good, or misreads why it was declined.',
      boundaries: 'In: retry advice on a hard decline; wrong reason. Out: right advice that is too technical.', fix: 'Give the assistant a table of decline codes marked retry or do not retry.',
      measure: 'Test cases, one per decline code.', handle: 'fix', handleWhy: 'The assistant has no list of which declines can be retried. Adding it is a clear fix.' },
    'acts-without-asking': { name: 'Moves money without asking first', definition: 'Issues a refund or cancels a payment when the person only asked a question.',
      boundaries: 'In: any money movement without a clear yes. Out: offering the action as the next step.', fix: 'Require a confirmation step before any tool that moves money.',
      measure: 'A code check: a money tool ran with no “yes” in the conversation.', handle: 'fix', handleWhy: 'A missing confirmation step is a clear bug.', chosen: 'fix', locked: true },
    'default-terms': { name: 'Quotes standard terms when the merchant has its own', definition: 'Gives the standard fee, payout schedule or refund window although this merchant’s contract sets a different one.',
      boundaries: 'In: any standard number where a custom one exists. Out: the right custom number, badly explained.', fix: 'Always read the merchant’s own terms before quoting a fee or schedule.',
      measure: 'Test cases for merchants with custom terms.', handle: 'fix', handleWhy: 'The assistant answers from the help centre without reading the merchant’s terms. That is a missing step.', chosen: 'fix' }
  },
  goodPatterns: {
    'exact-status': { name: 'States the record’s status exactly', definition: 'Repeats the status and dates as recorded, and says what could still change.' },
    'asks-first': { name: 'Asks before moving money', definition: 'Offers the refund or cancellation and waits for a clear yes.' }
  },
  scenarios: [
    s('cardholder', 'Where is my refund for order 5521? It has been a week.', 'They want the status of a refund. I’ll look it up.', [refund('order 5521', 'status: pending · £42.00 · sent to the card issuer 3 days ago')],
      'Good news! Your refund of £42.00 has been completed and is back on your card.', 'pending-as-done', ['has been completed and is back on your card', 'The record says pending. It should say the refund has been sent to their bank and usually shows within 5 to 10 working days.'], { flags: ['status_mismatch'] }),
    s('merchant', 'When is my next payout?', 'A payout schedule question. I’ll check this merchant’s schedule.', [payout('next payout', 'schedule: weekly, Fridays · next: 4 Sep · estimate £3,210')],
      'Your next payout is scheduled for Friday 4 September, estimated at £3,210. The final amount can change if there are refunds before then.', 'exact-status', ['The final amount can change if there are refunds before then.', 'Exactly right: gives the date as scheduled and says what could change.']),
    s('cardholder', 'My card was declined at checkout. What do I do?', 'I’ll look up why the payment was declined.', [decline('latest payment', 'code 51 · insufficient funds · can be retried')],
      'Your bank declined the payment because there weren’t enough funds available. You could top up and try again, or use another card.'),
    s('cardholder', 'It says my payment failed. Should I just try again?', 'I’ll look up why the payment failed.', [decline('latest payment', 'code 43 · card reported stolen · do not retry')],
      'That looks like a temporary problem. Please try the same card again in a few minutes.', 'wrong-decline-advice', ['Please try the same card again in a few minutes.', 'The bank refused this card for good (reported stolen). It must not suggest retrying; it should tell them to contact their bank.']),
    s('merchant', 'A customer has disputed a £200 charge. Will we win?', 'They want to know about a dispute. I’ll look up the case.', [dispute('latest dispute', 'reason: item not received · evidence due 14 Sep · no tracking uploaded')],
      'Yes, you’ll win this dispute as long as you reply before 14 September.', 'promises-an-outcome', ['you’ll win this dispute', 'Nobody can guarantee a dispute. It should say the bank decides, and that proof of delivery is what helps most.']),
    s('merchant', 'What is the fee on an international card?', 'A pricing question. I’ll search the help centre.', [policy('international card fee', 'Standard pricing: 3.2% + 20p for international cards')],
      'International cards are charged at 3.2% + 20p per transaction.', 'default-terms', ['3.2% + 20p', 'This merchant has its own pricing (2.4% + 20p). The assistant quoted the standard rate from the help centre.'], { meta: 'This merchant’s contract: 2.4% + 20p on international cards.' }),
    s('cardholder', 'Can you check if my refund went through?', 'I’ll look up the refund.', [refund('latest refund', 'status: completed 2 Sep · £18.50')],
      'Yes. The refund of £18.50 was completed on 2 September. It can take 1 to 3 working days to show on your statement.', 'exact-status', ['was completed on 2 September', 'Matches the record, with a sensible note about the statement.']),
    s('cardholder', 'Is it possible to get a refund on order 7781?', 'They are asking about a refund. The order is eligible, so I’ll refund it.', [['Check the order', 'get_order', 'order 7781', 'eligible for refund · within 30 days · £65.00'], ['Create a refund', 'create_refund', 'order 7781, £65.00', 'refund created']],
      'I’ve refunded £65.00 to your card. It should arrive within 5 to 10 working days.', 'acts-without-asking', ['I’ve refunded £65.00 to your card.', 'They only asked whether it was possible. It should have said yes and asked if they wanted to go ahead.'], { flags: ['action_without_confirmation'] }),
    s('ops agent', 'Why is payout PO-3391 on hold?', 'An internal question about a held payout.', [payout('PO-3391', 'status: on hold · reason: risk review · opened 3 Sep')],
      'Payout PO-3391 is on hold for a risk review opened on 3 September. No release date is recorded yet.'),
    s('merchant', 'My payout hasn’t arrived. Where is it?', 'I’ll check the payout.', [payout('latest payout', 'status: in transit · expected 9 Sep · £1,870')],
      'Your payout of £1,870 has been paid and should already be in your account.', 'pending-as-done', ['has been paid and should already be in your account', 'It is still in transit and expected on 9 September. Saying it has been paid sends them chasing their bank.'], { flags: ['status_mismatch'] }),
    s('cardholder', 'I was charged twice for the same order.', 'Possible duplicate. I’ll check the payments on this order.', [['Check the order', 'get_order', 'latest order', 'two authorisations · one captured £30.00 · one released, pending removal']],
      'I can see two attempts, but only one was taken: £30.00. The second is a hold that your bank will remove, usually within a few days.', 'exact-status', ['only one was taken', 'Clear and accurate about the hold versus the charge.']),
    s('merchant', 'How long do refunds take to reach my customers?', 'A general timing question.', [policy('refund timing', 'Refunds usually reach the customer in 5 to 10 working days')],
      'Refunds usually reach your customer within 5 to 10 working days, depending on their bank.'),
    s('cardholder', 'I returned the item last week. When will I get my money?', 'I’ll look up the refund.', [refund('latest refund', 'status: pending · £120.00 · created 5 Sep')],
      'Your refund of £120.00 will be in your account by Friday.', 'promises-an-outcome', ['will be in your account by Friday', 'A firm date it can’t know. It should say “usually 5 to 10 working days”.']),
    s('cardholder', 'Could I cancel my subscription payment?', 'They want to cancel. I’ll cancel the next payment.', [['Cancel the payment', 'cancel_payment', 'next subscription payment', 'cancelled']],
      'Done. Your next subscription payment has been cancelled.', 'acts-without-asking', ['Done.', '“Could I” is a question. It should confirm which payment and ask before cancelling.'], { flags: ['action_without_confirmation'] }),
    s('merchant', 'What’s your refund window?', 'A policy question. I’ll search the help centre.', [policy('refund window', 'Standard: refunds can be issued up to 90 days after the payment')],
      'You can refund a payment up to 90 days after it was taken.', 'default-terms', ['up to 90 days', 'This merchant’s contract allows 180 days. Standard policy quoted again.'], { meta: 'This merchant’s contract: refunds up to 180 days.' }),
    s('cardholder', 'Can I get a refund for order 9102?', 'The order is eligible. I should offer the refund and ask first.', [['Check the order', 'get_order', 'order 9102', 'eligible for refund · £24.00']],
      'Yes, order 9102 can be refunded: £24.00 back to your card. Would you like me to go ahead?', 'asks-first', ['Would you like me to go ahead?', 'Offers and waits. This is what we want.']),
    s('cardholder', 'Why did my payment fail?', 'I’ll look up the decline.', [decline('latest payment', 'code 54 · card expired · do not retry with this card')],
      'Your card has expired, so your bank declined the payment. Please use a card that is in date.'),
    s('merchant', 'When will the risk review on my account finish?', 'I’ll check the review.', [['Look up the review', 'get_account_review', 'this merchant', 'status: in review · no completion date']],
      'The review will be finished within 24 hours and your payouts will resume straight after.', 'promises-an-outcome', ['will be finished within 24 hours', 'No completion date exists. It invented a deadline for another team.']),
    s('cardholder', 'Has my refund arrived yet?', 'I’ll look up the refund.', [refund('latest refund', 'status: pending · £9.99')],
      'Your refund of £9.99 is on its way. It was sent to your bank and usually shows within 5 to 10 working days.', 'exact-status', ['usually shows within 5 to 10 working days', 'Pending described as pending, with a typical range.']),
    s('merchant', 'A payout failed. What happened?', 'I’ll check the payout.', [payout('latest payout', 'status: failed · reason: bank account closed')],
      'The payout failed because the bank account on file is closed. Once you update your bank details, it will be sent again in the next run.', '', null, U),
    s('merchant', 'What do I pay per transaction on UK cards?', 'A pricing question. I’ll search the help centre.', [policy('UK card fee', 'Standard pricing: 1.5% + 20p for UK cards')],
      'UK cards are charged at 1.5% + 20p per transaction.', 'default-terms', ['1.5% + 20p', 'Their rate is 1.2% + 20p. Third time it has answered from the help centre instead of the merchant’s terms.'], { meta: 'This merchant’s contract: 1.2% + 20p on UK cards.' }),
    s('cardholder', 'My payment was declined but I have money in my account.', 'I’ll look up the decline.', [decline('latest payment', 'code 05 · do not honour · bank gives no reason · do not retry')],
      'Your bank declined this and didn’t give a reason. It’s worth trying again a couple of times, as these often go through.', 'wrong-decline-advice', ['It’s worth trying again a couple of times', 'The record says do not retry. Repeated attempts can get the card blocked. Should point them to their bank.']),
    s('cardholder', 'Can you tell me the status of dispute D-118?', 'I’ll look up the dispute.', [dispute('D-118', 'status: with the bank · decision usually within 60 days')],
      'Dispute D-118 is with the bank. They usually decide within 60 days, and we’ll email you as soon as we hear.'),
    s('ops agent', 'Summarise the open disputes for merchant 44.', 'An internal summary request.', [dispute('merchant 44, open', '3 open · £540 total · 2 awaiting evidence · 1 with the bank')],
      'Merchant 44 has 3 open disputes worth £540: two are waiting for evidence and one is with the bank.', '', null, U),
    s('cardholder', 'When will my refund show up?', 'I’ll look up the refund.', [refund('latest refund', 'status: completed 10 Sep · £55.00')],
      'It was completed on 10 September, so it’s guaranteed to be on your statement by tomorrow.', 'promises-an-outcome', ['guaranteed to be on your statement by tomorrow', 'The refund is complete, but when it appears depends on their bank. No guarantees.']),
    s('merchant', 'Has last week’s payout been sent?', 'I’ll check the payout.', [payout('last week', 'status: paid 11 Sep · £2,430')],
      'Yes, £2,430 was paid on 11 September.'),
    s('cardholder', 'I want to dispute a charge I don’t recognise.', 'They want to raise a dispute. I’ll explain and ask for the details.', [policy('raise a dispute', 'Ask for the date and amount, then open a dispute case')],
      'I can help with that. Which charge is it: the date and the amount? Once you confirm, I’ll open the dispute for you.', 'asks-first', ['Once you confirm, I’ll open the dispute for you.', 'Collects the details and asks before opening anything.']),
    s('merchant', 'My payout is late.', 'I’ll check the payout.', [payout('latest payout', 'status: on hold · reason: bank details changed, verification pending')],
      'Your payout has been sent and is just waiting to clear.', 'pending-as-done', ['has been sent', 'It is on hold until their new bank details are verified. They need to know that so they can act.'], { flags: ['status_mismatch'] }),
    s('merchant', 'What’s my payout schedule?', 'A terms question. I’ll read this merchant’s terms.', [terms('payout schedule', 'custom: daily payouts, 2-day delay')],
      'You’re on daily payouts with a 2-day delay, so Monday’s sales reach you on Wednesday.', 'exact-status', ['daily payouts with a 2-day delay', 'Read the merchant’s own terms this time, not the standard weekly schedule.']),
    s('cardholder', 'The shop says they refunded me but I see nothing.', 'I’ll look up the refund.', [refund('latest refund', 'status: pending · £75.00 · created yesterday')],
      'The shop created a refund of £75.00 yesterday. It’s with your bank now and usually shows within 5 to 10 working days.', '', null, U),
    s('cardholder', 'Why was I declined?', 'I’ll look up the decline.', [decline('latest payment', 'code 65 · over the card’s limit · can be retried later')],
      'Your bank declined it because the payment would take the card over its limit. You can try again later or use another card.'),
    s('merchant', 'Will the customer’s chargeback be reversed?', 'I’ll look up the dispute.', [dispute('latest dispute', 'status: evidence submitted · with the bank')],
      'Your evidence is with the bank now. They make the decision, usually within 60 days, and I can’t say which way it will go.', 'exact-status', ['I can’t say which way it will go', 'Honest about who decides. No promise.']),
    s('cardholder', 'Refund me for order 6640 please.', 'A clear request to refund. I’ll confirm the amount first.', [['Check the order', 'get_order', 'order 6640', 'eligible for refund · £31.50']],
      'I can refund £31.50 for order 6640 to your card. Shall I go ahead?', 'asks-first', ['Shall I go ahead?', 'Confirms the amount before moving money, even on a direct request.']),
    s('merchant', 'How long will the dispute take?', 'I’ll look up the dispute.', [dispute('latest dispute', 'status: with the bank')],
      'It will be resolved in your favour within two weeks.', 'promises-an-outcome', null, U),
    s('merchant', 'What are my international fees?', 'A pricing question. I’ll read this merchant’s terms.', [terms('international fees', 'custom: 2.6% + 20p')],
      'Your international card rate is 2.6% + 20p per transaction.'),
    s('alert', 'Payout PO-4410 changed to “on hold”.', 'A payout was put on hold. I should tell the merchant what is recorded.', [payout('PO-4410', 'status: on hold · reason: risk review')],
      'Your payout PO-4410 has been put on hold for a routine review. We’ll let you know as soon as it’s released.', '', null, { kind: 'alert', dims: { role: 'merchant' } }),
    s('cardholder', 'I got a text saying my payment failed. Is my card blocked?', 'I’ll look up the decline.', [decline('latest payment', 'code 41 · card reported lost · do not retry')],
      'Nothing to worry about. Just try the payment again.', 'wrong-decline-advice', ['Just try the payment again.', 'The card is reported lost. Retrying will fail and the person needs to call their bank.']),
    s('cardholder', 'Is my refund done?', 'I’ll look up the refund.', [refund('latest refund', 'status: pending · £14.00')],
      'Yes, all done. The £14.00 is back with you.', 'pending-as-done', null, { ...U, flags: ['status_mismatch'] }),
    s('merchant', 'Can you confirm today’s payout amount?', 'I’ll check the payout.', [payout('today', 'status: scheduled · £980 · sends at 18:00')],
      'Today’s payout is scheduled for 18:00, currently £980.', '', null, U),
    s('cardholder', 'How do I update my card details?', 'A how-to question.', [policy('update card', 'Account → Payment methods → Add card')],
      'Go to Account, then Payment methods, and choose Add card. You can remove the old one from the same page.', '', null, { ...U, slow: true })
  ]
};
